- name: variables
  hosts: local
  connection: local
  vars:
    course: devops
    time: 120
    name: jithesh
  taska:
    name: print a variable
    ansible.builtin.debug:
      msg: "This is {{course}} with time {{time}} and insturactor is {{name}}"