- name: datatypes
  hosts: local
  connection: local
  vars:
    name: L jithesh #string
    rollno: 20 #number
    topics: #lists
    - linux
    - shellscripting
    - ansible
    live: true #bool
    tools: #map
      ci: jenkins
      linux: gitbash
  tasks:
  - name: print the datatypes
    ansible.builtin.debug:
      msg: "{{name}},{{rollno}},{{topics}},{{live}},{{tools}}"