- name : install nginx
  hosts: web
  become: yes
  tasks:
  - name: install if os is redhat
    ansible.builtin.dnf:
      name: nginx
      state: started
    when:  ansible_os_family == "RedHat"
  - name: install if os is ubuntu
    ansible.builtin.apt:
      name: nginx
      state: started
    when : ansible_os_family == "Debian"

