- name : loops
  hosts: local
  connection: local
  tasks:
  - name: print loop
    ansible.builtin.debug:
      msg: "Hello {{item}}"
    loop:
    - prompt: enter the  name:-
      private: false
    - prompt: enter the  name:-
      private: false
    - prompt: enter the   name:-
      private: false