- name: install package in loop
  hosts: web
  become: yes
  tasks:
  - name: install package in loop
    ansible.builtin.dnf:
      name: "{{item}}"
      state: installed
    loop:
    - git 
    - mysql
    - nginx
