- name: install and deletion of package
  hosts: web
  become: yes
  tasks:
  - name: install and deletion of package
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'git', state: 'present'}
    - {name: 'mysql', state: 'absent'}
    - {name: 'git', state: 'absent'}
    - {name: 'zip', state: 'present'}