- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle the undefined variables
    ansible.builtin.debug:
      msg: "Hello {{person | default('Jithesh')}}"
  - name: convert string to list
    vars:
      fruits: "apple,banana,orange"
    ansible.builtin.debug:
      msg: "{{fruits | split(',')}}"
  - name: convert map to list
    vars:
      course:
        name: devops
        duration: 120hrs
        trainer: shivakumar
    ansible.builtin.debug:
      msg: "course info:- {{course | dict2items}}"
