- name: shell vs command
  hosts: local
  tasks:
  # - name: excecute  ls command
  #   ansible.builtin.command: ls -ltr > tmp/output.txt
  - name: excecute  ls command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
  # - name: excecute  ls command
  #   ansible.builtin.command: ls -ltr 